[package]
name = "redbpf-macros"
description = "Procedural macros for redbpf"
repository = "https://github.com/redsift/redbpf"
documentation = "https://redsift.github.io/rust/redbpf/doc/redbpf_macros/"
authors = ["Alessandro Decina <alessandro.d@gmail.com>", "Peter Parkanyi <peter@redsift.io>"]
version = "0.9.4"
edition = '2018'
keywords = ["bpf", "ebpf", "redbpf"]
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = {version = "1.0", features = ["full"] }
quote = "1.0"

[build-dependencies]
redbpf = { version = "^0.9.0", features = ["build"], path = "../redbpf" }
bindgen = "0.51"
syn = {version = "1.0", features = ["full", "visit-mut"] }
quote = "1.0"
