[package]
name = "cargo-bpf"
version = "0.9.4"
description = "Cargo plugin to manage eBPF probes using redbpf"
repository = "https://github.com/redsift/redbpf"
documentation = "https://redsift.github.io/rust/redbpf/doc/cargo_bpf/"
authors = ["Alessandro Decina <alessandro.d@gmail.com>", "Peter Parkanyi <peter@redsift.io>"]
edition = "2018"
keywords = ["cargo", "redbpf", "bpf", "plugin", "subcommand"]
categories = ["development-tools::cargo-plugins"]
license = "GPL-3.0"

[lib]
name = "cargo_bpf_lib"

[dependencies]
clap = "2.33"
bindgen = "0.51.1"
toml_edit = "0.1.5"
redbpf = { version = "^0.9.0", features = ["build"], path = "../redbpf" }
futures = "0.1"
mio = "0.6"
tokio = "0.1"
tokio-reactor = "0.1"
hexdump = "0.1"
