[package]
name = "cargo-bpf"
version = "1.1.0"
description = "Cargo plugin to manage eBPF probes using redbpf"
repository = "https://github.com/redsift/redbpf"
documentation = "https://ingraind.org/api//cargo_bpf/"
authors = ["Alessandro Decina <alessandro.d@gmail.com>", "Peter Parkanyi <peter@redsift.io>"]
edition = "2018"
keywords = ["cargo", "redbpf", "bpf", "plugin", "subcommand"]
categories = ["development-tools::cargo-plugins"]
license = "MIT OR Apache-2.0"

[lib]
name = "cargo_bpf_lib"

[dependencies]
clap = { version = "2.33", optional = true }
bindgen = "0.51.1"
toml_edit = "0.1.5"
bpf-sys = { version = "^1.1.0", path = "../bpf-sys" }
redbpf = { version = "^1.1.0", path = "../redbpf", default-features = false, optional = true }
futures = { version = "0.3", optional = true }
tokio = { version = "0.2.4", features = ["rt-core", "io-driver", "macros", "signal"], optional = true }
hexdump = { version = "0.1", optional = true }
libc = "0.2.66"
llvm-sys = "100"
syn = { version = "1.0", features = ["full", "visit"] }
quote = "1.0"
proc-macro2 = "1.0"
tempfile = "3.1"
lazy_static = "1.0"

[features]
default = ["command-line"]
build = []
build-c = []
command-line = ["clap", "redbpf/load", "futures", "tokio", "hexdump"]