[package]
name = "bpf-sys"
version = "0.9.4"
description = "Bindings for libbpf from BCC"
repository = "https://github.com/redsift/redbpf"
documentation = "https://redsift.github.io/rust/redbpf/doc/bpf_sys/"
authors = ["Peter Parkanyi <peter@redsift.io>"]
links = "bpf"
edition = "2018"
license = "GPL-3.0"
keywords = ["bpf", "ebpf", "ffi"]

[dependencies]
zero = "0.1"
libc = "0.2"

[build-dependencies]
cc = "1.0"
bindgen = "0.51"
libc = "0.2"
