[package]
name = "probes"
version = "0.1.0"
edition = '2018'

[build-dependencies]
cargo-bpf = { version = "^0.9.12", path = "../../cargo-bpf" }

[dependencies]
cty = "0.2"
redbpf-macros = { version = "^0.9.12", path = "../../redbpf-macros" }
redbpf-probes = { version = "^0.9.12", path = "../../redbpf-probes" }

[features]
default = []
probes = []

[lib]
path = "src/lib.rs"

[[bin]]
name = "iotop"
path = "src/iotop/main.rs"
required-features = ["probes"]

[[bin]]
name = "knock"
path = "src/knock/main.rs"
required-features = ["probes"]
