[package]
name = "redbpf-tools"
version = "0.1.0"
authors = ["Alessandro Decina <alessandro.d@gmail.com>"]
edition = "2018"

[build-dependencies]
cargo-bpf = { version = "^1.3.0", path = "../cargo-bpf", default-features = false, features = ["build"] }

[dependencies]
probes = { path = "./probes" }
redbpf = {  version = "^1.3.0", path = "../redbpf", features = ["load"] }
tokio = { version = "^1.0.1", features = ["rt", "macros", "signal", "time"] }
futures = "0.3"
getopts = "0.2"
libc = "0.2"
